# Generated by Django 3.0 on 2020-05-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=32)),
                ('phone', models.CharField(default=None, max_length=11, null=True)),
                ('sex', models.IntegerField(choices=[[0, '男'], [1, '女']], default=0)),
                ('head_pic', models.ImageField(default='head_pic/2.jpg', upload_to='head_pic')),
                ('img', models.ImageField(default='img/2.jpg', upload_to='img')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'db_table': 'bz_emp',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=32)),
                ('phone', models.CharField(default=None, max_length=11, null=True)),
                ('sex', models.IntegerField(choices=[[0, '男'], [1, '女']], default=0)),
                ('head_pic', models.ImageField(default='head_pic/2.jpg', upload_to='head_pic')),
                ('img', models.ImageField(default='img/2.jpg', upload_to='img')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'db_table': 'bz_employee',
            },
        ),
    ]
