# Generated by Django 3.0 on 2020-05-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='head_pic',
        ),
    ]
