# Generated by Django 3.0 on 2020-05-09 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seria', '0002_remove_employee_head_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emp',
        ),
    ]
