# Generated by Django 3.0 on 2020-05-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('sex', models.SmallIntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'others')], default=1)),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'db_table': 'bz_student',
            },
        ),
    ]
